### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by ripienaar** [comment]
Should be easier after https://github.com/choria-io/mcorpc-ruby-support/pull/198 as I fixced the tests for ruby 3.2.3

**Comment by smortex** [comment]
> Should be easier after #198 as I fixced the tests for ruby 3.2.3

Ah yeah, I left this on the side for in a few weeks :wink:  I am about to go for a few days to a place without computers, before leaving I rebased on top of main, everything is not as smooth as at could, but I at leas I got the test suite passing for some test matrix configuration:
https://github.com/smortex/mcorpc-ruby-support/actions/runs/9773220201/job/26978954896?pr=1

Improving the "health" of the ruby ecosystem and CI is one of my main goals for the holidays.

More work will follow up in the next weeks

**Comment by smortex** [comment]
It finally pass (went slower than expected… holidays… :smile:)!
https://github.com/smortex/mcorpc-ruby-support/actions/runs/10383582056?pr=1

Some changes are really not nice, the testing library feels quite weak, but at least CI now pass on what I think is all the versions of Ruby we should support.

**Comment by smortex** [comment]
I think this one is now ready for merging :tada:

**Comment by ripienaar** [comment]
Thank you!

**Pull request merged**
