### PR TITLE
(#190) Allow setting SRV domain using environment variable

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
The failures are related to ERB.new usage and Rubocop autocorrect wants to do this:

```diff
$ git diff
diff --git a/lib/mcollective/pluginpackager/forge_packager.rb b/lib/mcollective/pluginpackager/forge_packager.rb
index ca8ff4b5..3602459e 100644
--- a/lib/mcollective/pluginpackager/forge_packager.rb
+++ b/lib/mcollective/pluginpackager/forge_packager.rb
@@ -191,7 +191,7 @@ module MCollective
       end

       def render_template(infile, outfile)
-        erb = ERB.new(File.read(infile), safe_level:0, trim_mode:"-")
+        erb = ERB.new(File.read(infile), :safe_level => 0, :trim_mode => "-")
         File.open(outfile, "w") do |f|
           f.puts erb.result(binding)
         end
```

I can make this change but wasn't sure if this might cause issues with Ruby 3.2 for Puppet 8.

**Comment by treydock** [comment]
The unit tests failing appear to be unrelated to what I changed.

**Comment by ripienaar** [comment]
Looks good to me, CI failure does seem unrelated.

**Comment by treydock** [comment]
@smortex @ripienaar Let me know if anything needed on this PR.  Hoping this merged before next set of releases.

**Pull request merged**
