### PR TITLE
(#69) Add FreeBSD support

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by ripienaar** [comment]
That's weird, did the old mco gem really have these in there? Guess I could have accidentally cleaned them up - I deleted over 30 000 lines of code from this.  Seems good anyway

**Comment by smortex** [comment]
No, the old mcollective gem does not have this, but the FreeBSD port had local patches to make it work:

```make
post-patch:
        @${REINPLACE_CMD} -e "s|/etc/mcollective|${ETCDIR}|" \
            ${WRKSRC}/bin/mcollectived \
                ${WRKSRC}/etc/server.cfg.dist \
                ${WRKSRC}/etc/client.cfg.dist \
                ${WRKSRC}/lib/mcollective/config.rb \
                ${WRKSRC}/lib/mcollective/util.rb \
                ${WRKSRC}/lib/mcollective/rpc.rb
        @${REINPLACE_CMD} -e "s|/usr/libexec/mcollective|${PREFIX}/share|" \
            ${WRKSRC}/etc/server.cfg.dist \
            ${WRKSRC}/etc/client.cfg.dist
```

Only the file touched in this PR seems to still have references to `/etc`.  I did not though about the config files templates because Puppet will replace them with correct content… but in a Puppet-less environment maybe it makes sense to fix them too?

**Comment by ripienaar** [comment]
yeah those templates are really just never used for anything anymore, I should just delete them :)

**Comment by smortex** [comment]
Fine, I can forget about them then. Thanks!

**Pull request merged**
